### ISSUE TITLE
How to report issues?

### ISSUE THREAD

**Issue by bassjacob** [jesstelford/extract-to-react#2]
So I have a pen that fails, but I don't have a real way to report it. Maybe the generator could output a hash that can be used to deterministically retry builds to test and retest features?

url + xpath or something?

**Comment by jesstelford** [comment]
Yeah, maybe a url encoded string as a comment at the head of the JS code?

``` javascript
// Not working? Report it here: https://github.com/jesstelford/extract-to-react/issues/new?body=<url-encoded-version-of-output>

var Component = React.creactClass({ ...
```

**Comment by jesstelford** [comment]
Added in 17f4c0abe18b211ac26618c3baffcb757ea84277

Definitely room for improvement, but is a start :)
