### ISSUE TITLE
when generating a styles object, if the first key is margin the value is not followed by a comma, making the object invalid

### ISSUE THREAD

**Issue by bassjacob** [jesstelford/extract-to-react#3]
when I visit github.com
when I am logged in
when I open developer tools
when I select the elements tab
when I select the div that has the class header header-logged-in true
when I select the Extract To React tab
when I click the codepen button
the generated javascript contains two errors

**Comment by bassjacob** [comment]
On commit sha: 1dff4d3ad9ea7e63709d27c7beaa9414de1b6d65
On browser Version 47.0.2526.111 (64-bit)
On O/S Ubuntu Linux 15.10

**Comment by jesstelford** [comment]
Looks like this is an issue in roman01la/html-to-react-components#9

**Comment by roman01la** [comment]
_html-to-react-components_ author here. The issue was fixed ;)

**Comment by jesstelford** [comment]
Fixed in 791ea46. Thanks so much for the update @roman01la - you've gone above and beyond :)
